workflows: bump MSRV to 1.51.0
Avoid CI failure with a dependency requiring the new resolver:

    Downloaded crypto-common v0.1.4
    error: failed to parse manifest at `/home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/crypto-common-0.1.4/Cargo.toml`
    Caused by:
      feature `resolver` is required
      this Cargo does not support nightly features, but if you
      switch to nightly channel you can add
      `cargo-features = ["resolver"]` to enable this feature